### ISSUE TITLE
ボドゲ部の創立

### ISSUE THREAD

**Issue by axross** [aibou/aibou#1]
- [ ] 予算の確保
- [ ] メンバーの確保 (5人〜)
- [ ] ボドゲ棚の設置

**Comment by aibou** [comment]
がんばるぞい

**Comment by aibou** [comment]
予算：ポーカー部に間借り
メンバー：たぶん5人には達したはず
ボドゲ棚：本棚間借りした

**Comment by aibou** [comment]
もうゴールしてもいいよね

**Comment by aibou** [comment]
ごおおおおおおおおおおおおおおおおおおおおおおおおおおおおおおる
