### ISSUE TITLE
scala覚える

### ISSUE THREAD

**Issue by aibou** [aibou/aibou#2]

**Comment by kyokomi** [comment]
:+1:

**Comment by nhayato** [comment]
:+1:

**Comment by aibou** [comment]
合宿でgatling書く

**Comment by aibou** [comment]
よくわからん

**Comment by aibou** [comment]
https://github.com/gatling/gatling/blob/master/gatling-core/src/main/scala/io/gatling/core/scenario/Simulation.scala
リーディングしてる
