### ISSUE TITLE
ふるさと納税始める

### ISSUE THREAD

**Issue by aibou** [aibou/aibou#5]
何にしよう

**Comment by ysekky** [comment]
最高のUXだった
http://www.furusato-tax.jp/japan/prefecture/item_detail/01208/117155

**Comment by aibou** [comment]
メッチャよさそう

**Comment by aibou** [comment]
間に合わなかった。今年こそは

**Comment by aibou** [comment]
去年もできなかった。やる気ないのでは

**Comment by aibou** [comment]
去年やったのでdone。今年もがんばろう
